name: Build LÖVE Android

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Clean project
        run: ./gradlew clean
      - name: Build
        run: |
          ./gradlew assembleNormalRecord assembleEmbedRelease bundleNormalNoRecordRelease bundleEmbedRecordRelease bundleEmbedNoRecordRelease

      - name: Artifact (Normal debug APK)
        uses: actions/upload-artifact@v4
        with:
          name: love-android-debug.apk
          path: app/build/outputs/apk/normalRecord/debug/app-normal-record-debug.apk

      - name: Artifact (Normal unsigned APK)
        uses: actions/upload-artifact@v4
        with:
          name: love-android.apk
          path: app/build/outputs/apk/normalRecord/release/app-normal-record-release-unsigned.apk

      - name: Artifact (Normal AAB w/o recording)
        uses: actions/upload-artifact@v4
        with:
          name: love-android-ps.aab
          path: app/build/outputs/bundle/normalNoRecordRelease/app-normal-noRecord-release.aab

      - name: Artifact (Embed AAB)
        uses: actions/upload-artifact@v4
        with:
          name: love-android-embed-record.aab
          path: app/build/outputs/bundle/embedRecordRelease/app-embed-record-release.aab

      - name: Artifact (Embed AAB w/o recording)
        uses: actions/upload-artifact@v4
        with:
          name: love-android-embed.aab
          path: app/build/outputs/bundle/embedNoRecordRelease/app-embed-noRecord-release.aab
